apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.name" . }}-backend
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.backend.POSTGRES_PASSWORD |b64enc }}
  JWT_KEY: {{ .Values.backend.JWT_KEY | b64enc }}
